#!/bin/bash
cd "$(git rev-parse --show-toplevel)"
source .debug/bin/activate
reformat=false

if git diff --cached --name-only | grep -q '\.py$'; then
    reformat=true
    file_name=$(git diff --cached --name-only | grep '\.py$')
    echo "[pre-commit]: running isort..."
    isort $file_name
    echo "[pre-commit]: running black..."
    black $file_name -l 100
    git add $file_name
fi
if git diff --cached --name-only | grep -q '\.html$'; then
    reformat=true
    file_name=$(git diff --cached --name-only | grep '\.html$')
    echo "[pre-commit]: running prettier..."
    prettier $file_name -w
    echo "[pre-commit]: running djlint..."
    djlint $file_name --reformat --indent 2
    git add $file_name
fi
if git diff --cached --name-only | grep -q '\.css$'; then
    reformat=true
    file_name=$(git diff --cached --name-only | grep '\.css$')
    echo "[pre-commit]: running prettier..."
    prettier $file_name -w
    git add $file_name
fi
if [ $reformat == "true" ]; then
    echo "[pre-commit]: done"
    echo ""
fi